//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.12 at 02:11:13 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dummy-core-bank.com/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dummy_core_bank.ws;
