//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.12 at 01:21:48 PM IST 
//


package com.task.schemas.corebank;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fundTransferInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fundTransferInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="debitUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debitAccountNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debitAccountBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="creditUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditAccountNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditAccountBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fundTransferInfo", propOrder = {
    "debitUserId",
    "debitAccountNo",
    "debitAccountBalance",
    "creditUserId",
    "creditAccountNo",
    "creditAccountBalance"
})
public class FundTransferInfo {

    @XmlElement(required = true)
    protected String debitUserId;
    @XmlElement(required = true)
    protected String debitAccountNo;
    @XmlElement(required = true)
    protected BigDecimal debitAccountBalance;
    @XmlElement(required = true)
    protected String creditUserId;
    @XmlElement(required = true)
    protected String creditAccountNo;
    @XmlElement(required = true)
    protected BigDecimal creditAccountBalance;

    /**
     * Gets the value of the debitUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitUserId() {
        return debitUserId;
    }

    /**
     * Sets the value of the debitUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitUserId(String value) {
        this.debitUserId = value;
    }

    /**
     * Gets the value of the debitAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitAccountNo() {
        return debitAccountNo;
    }

    /**
     * Sets the value of the debitAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitAccountNo(String value) {
        this.debitAccountNo = value;
    }

    /**
     * Gets the value of the debitAccountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDebitAccountBalance() {
        return debitAccountBalance;
    }

    /**
     * Sets the value of the debitAccountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDebitAccountBalance(BigDecimal value) {
        this.debitAccountBalance = value;
    }

    /**
     * Gets the value of the creditUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditUserId() {
        return creditUserId;
    }

    /**
     * Sets the value of the creditUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditUserId(String value) {
        this.creditUserId = value;
    }

    /**
     * Gets the value of the creditAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditAccountNo() {
        return creditAccountNo;
    }

    /**
     * Sets the value of the creditAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditAccountNo(String value) {
        this.creditAccountNo = value;
    }

    /**
     * Gets the value of the creditAccountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditAccountBalance() {
        return creditAccountBalance;
    }

    /**
     * Sets the value of the creditAccountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditAccountBalance(BigDecimal value) {
        this.creditAccountBalance = value;
    }

}
