//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.12 at 01:21:48 PM IST 
//


package com.task.schemas.corebank;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="totalUserAccountBalanceInfo" type="{http://www.dummy-core-bank.com/ws}totalUserAccountBalanceInfo"/&gt;
 *         &lt;element name="serviceStatus" type="{http://www.dummy-core-bank.com/ws}serviceStatus"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalUserAccountBalanceInfo",
    "serviceStatus"
})
@XmlRootElement(name = "getTotalAccountBalanceResponse")
public class GetTotalAccountBalanceResponse {

    @XmlElement(required = true)
    protected TotalUserAccountBalanceInfo totalUserAccountBalanceInfo;
    @XmlElement(required = true)
    protected ServiceStatus serviceStatus;

    /**
     * Gets the value of the totalUserAccountBalanceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TotalUserAccountBalanceInfo }
     *     
     */
    public TotalUserAccountBalanceInfo getTotalUserAccountBalanceInfo() {
        return totalUserAccountBalanceInfo;
    }

    /**
     * Sets the value of the totalUserAccountBalanceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalUserAccountBalanceInfo }
     *     
     */
    public void setTotalUserAccountBalanceInfo(TotalUserAccountBalanceInfo value) {
        this.totalUserAccountBalanceInfo = value;
    }

    /**
     * Gets the value of the serviceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceStatus }
     *     
     */
    public ServiceStatus getServiceStatus() {
        return serviceStatus;
    }

    /**
     * Sets the value of the serviceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceStatus }
     *     
     */
    public void setServiceStatus(ServiceStatus value) {
        this.serviceStatus = value;
    }

}
